CREATE TABLE `files` (
 `id` varchar(14) NOT NULL,
 `iv` varchar(16) NOT NULL,
 `metadata` text NOT NULL,
 `content` mediumblob NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1


CREATE DEFINER=`root`@`localhost` EVENT `DELETE OLD FILES` ON SCHEDULE EVERY 1 DAY STARTS '2016-01-01 00:00:00' ON COMPLETION NOT PRESERVE ENABLE COMMENT 'DELETE OLD FILES' DO DELETE FROM `files` WHERE `time` < DATE_SUB(NOW(), INTERVAL 1 DAY)